### ISSUE TITLE
Param should be Interface, realization given

### ISSUE THREAD

**Issue by MetalRex101** [sarulabs/dingo#12]
It looks like it's correct behaviour, when concrete realization passed as parameter to method, which waits for interface that realization implements.

I think it could be fixed with adding `reflect.TypeOf().Implements()` check.
What do you think?

**Comment by sarulabs** [comment]
Hello, I think I fixed the problem in a `v4.0.1` version.
Implementation of interfaces can now be passed as parameter.
Can you check that it is what you wanted ?

**Comment by MetalRex101** [comment]
@sarulabs, thank you so much for such a quick response and patch! Now it is possible to pass interface as parameter, but in generated container file it adds package, which contains interface, but this package is not really used in that file. Because of that compile error occurs: `container/gen/dic/container.go:14:2: imported and not used: [package_name]`.
It could be fixed by manual deleting unused package import.

Could such imports be resolved at generation step and removed?

**Comment by sarulabs** [comment]
I fixed it (by using goimports instead of gofmt).

**Comment by MetalRex101** [comment]
Everything works correct now! Thank you!
