### ISSUE TITLE
Error on attempt to cast function with `ed25519.PrivateKey` argument

### ISSUE THREAD

**Issue by metalrex100** [sarulabs/dingo#17]
Hello,

Thank you very much for this container, it helps a lot with decreasing client's code amount.

I faced with the problem of using `ed25519.PrivateKey` type (wrapper for `[]byte` type)  within Builder function.
My `Builder` function looks like:

```
func(config *infra.Config) (ed25519.PrivateKey, error)
```

When I'm trying to build container, I get error:

`could not cast build function to func(*infra.Config) ([]uint8, error)`

Possible workaround: change argument type from `ed25519.PrivateKey` to `[]byte`.

**Comment by sarulabs** [comment]
Hello,

I was able to reproduce your error. There was a problem in the way types were registered in the library.

I created a new release `v4.0.3` that should fix the issue. Can you check if your project works with this new version?

**Comment by metalrex100** [comment]
With `v4.0.3` everything works like expected.

Thank you for such a fast response and fix!

Closing this issue.
