### ISSUE TITLE
Add ability to use slice of services in Params field

### ISSUE THREAD

**Issue by metalrex100** [sarulabs/dingo#26]
Hello there.
It would be really nice to be able to use in Params not map, but slice.
If Params field used for services - map keys are just indexes. The slice can be used. It is pretty annoying to edit all indexes if some param has been added to the middle of the params list.
I believe it is done in that way to use Params for different cases, but if you can add another field like SliceParams - it would be fantastic.

**Comment by sarulabs** [comment]
Hello,
I added a new function to generate the parameters:
https://github.com/sarulabs/dingo/pull/27/files
I created a new version `v4.2.0`.

**Comment by metalrex100** [comment]
@sarulabs function-constructor seems like very elegant and easy solution!
Thank you, will check!

**Comment by metalrex100** [comment]
Work as expected, thank you.
